package com.pant.agritude

// A data class to hold strings for different languages.
data class AppStrings(
    val appName: String,
    val tabChat: String,
    val tabDashboard: String,
    val tabStories: String,
    val settings: String,
    val profile: String,
    val greeting: String,
    val chatInputLabel: String,
    val chatSendButton: String,
    val chatPrompt1: String,
    val chatResponse1: String,
    val chatPrompt2: String,
    val chatResponse2: String,
    val chatPrompt3: String,
    val chatResponse3: String,
    val dashboardTitle: String,
    val marketPriceTitle: String,
    val cropTomato: String,
    val currentPrice: String,
    val forecast: String,
    val profitLossTitle: String,
    val totalInvestment: String,
    val expectedRevenue: String,
    val netProfit: String,
    val storiesTitle: String,
    val storyCardTitle: String,
    val storyCardSubtitle: String,
    val storyCardContent: String,
    val readStoryButton: String,
    val profileTitle: String,
    val profileName: String,
    val profileLocation: String,
    val profileFarmSize: String,
    val settingsTitle: String,
    val languageSettings: String,
    val loadingMessage: String,
    val errorMessage: String,
    val noDataMessage: String,
    val priceTrend: String,
    val averagePrice: String,
    val currency: String,
    val market: String,
    val weatherAlert: String,
    val dummyWeatherAlert: String,
    val voiceInput: String,
    val attachFile: String,
    val speechToTextPrompt: String,
    val tomatoPrice: String,
    val onionPrice: String,
    val weatherTitle: String,
    // New strings added for ChatScreen features
    val chatHistory: String,
    val deleteHistory: String,
    val listening: String,
    val enterMessage: String,
    val send: String,
    val deleteChatHistory: String,
    val deleteConfirmation: String,
    val delete: String,
    val llmGenerating: String,
    val cancel: String,
    val askQuestion:String
)

// A simple object to provide strings in different languages.
object Strings {
    val english = AppStrings(
        appName = "AgriTude",
        tabChat = "Chat",
        tabDashboard = "Dashboard",
        tabStories = "Stories",
        settings = "Settings",
        profile = "Profile",
        llmGenerating = "Generating response...",
        greeting = "Hello! I'm AgriTude, your farming assistant. How can I help you today?",
        chatInputLabel = "Ask me anything about farming...",
        chatSendButton = "Send message",
        chatPrompt1 = "What's the best time to plant tomatoes?",
        chatResponse1 = "For tomatoes, the best planting time is after the last frost date in your area. In most regions, this is between March-May. Soil temperature should be at least 60°F (16°C).",
        chatPrompt2 = "Can you show me market prices for tomatoes?",
        chatResponse2 = "The current market price for tomatoes is ₹25/kg. A 10% price increase is expected next week.",
        chatPrompt3 = "What is the best crop to cultivate this season?",
        chatResponse3 = "Based on your location and soil type, I recommend cultivating groundnut or maize this season. Would you like a detailed report on either?",
        dashboardTitle = "Dashboard",
        marketPriceTitle = "Market Price Forecast - Tomatoes",
        cropTomato = "Crop: Tomato",
        currentPrice = "Current: ₹45/kg",
        forecast = "Predicted: ₹52/kg",
        profitLossTitle = "Profit & Loss Analysis",
        totalInvestment = "Total Investment: ₹25,000",
        expectedRevenue = "Expected Revenue: ₹35,000",
        netProfit = "Net Profit: ₹10,000 (40%)",
        storiesTitle = "Success Stories",
        storyCardTitle = "Ramesh's Success Story",
        storyCardSubtitle = "Ramesh Kumar, Punjab • 2 acres wheat farm",
        storyCardContent = "Ramesh was struggling with low wheat yields and rising input costs. His traditional farming methods weren't giving him the profits he needed to support his family.",
        readStoryButton = "Ask AgriTude how to apply this to your farm",
        profileTitle = "User Profile",
        profileName = "User Name: John Doe",
        profileLocation = "Location: Chennai, Tamil Nadu",
        profileFarmSize = "Farm Size: 5 acres",
        settingsTitle = "Settings",
        languageSettings = "Language",
        loadingMessage = "Loading data...",
        errorMessage = "Failed to load data.",
        noDataMessage = "No data available.",
        priceTrend = "Price Trend Chart Placeholder",
        averagePrice = "Avg Price",
        currency = "₹/kg",
        market = "Market",
        weatherAlert = "Weather Alert",
        dummyWeatherAlert = "Heavy rains expected in your area. Take necessary precautions to protect your crops.",
        voiceInput = "Voice input",
        attachFile = "Attach file",
        speechToTextPrompt = "Speak now...",
        tomatoPrice = "Tomato: ₹30 - ₹60 / kg",
        onionPrice = "Onion: ₹20 - ₹40 / kg",
        weatherTitle = "Weather",
        // New strings
        chatHistory = "Chat History",
        deleteHistory = "Delete History",
        listening = "Listening...",
        enterMessage = "Enter your message",
        send = "Send",
        deleteChatHistory = "Delete Chat History",
        deleteConfirmation = "Are you sure you want to delete chat history?",
        delete = "Delete",
        cancel = "Cancel",
        askQuestion = "askQuestion"
    )

    val tamil = AppStrings(
        appName = "அக்ரிடியூட்",
        tabChat = "அரட்டை",
        tabDashboard = "டேஷ்போர்டு",
        tabStories = "கதைகள்",
        settings = "அமைப்புகள்",
        profile = "பயனர் சுயவிவரம்",
        greeting = "வணக்கம்! நான் உங்கள் தனிப்பட்ட AI உதவியாளர் அக்ரிடியூட். இன்று உங்களுக்கு எப்படி உதவ முடியும்?",
        chatInputLabel = "வேளாண்மை பற்றி ஏதாவது கேளுங்கள்...",
        chatSendButton = "மெசேஜ் அனுப்பு",
        chatPrompt1 = "தக்காளி நடவு செய்ய சிறந்த நேரம் எது?",
        chatResponse1 = "தக்காளியை நடவு செய்ய சிறந்த நேரம் உங்கள் பகுதியில் கடைசி உறைபனி தேதிக்குப் பிறகு. பெரும்பாலான பகுதிகளில், இது மார்ச்-மே மாதங்களுக்கு இடையில் இருக்கும். மண் வெப்பநிலை குறைந்தது 60°F (16°C) ஆக இருக்க வேண்டும்.",
        chatPrompt2 = "தக்காளியின் சந்தை விலைகளை எனக்குக் காட்ட முடியுமா?",
        chatResponse2 = "தக்காளியின் தற்போதைய சந்தை விலை ₹25/kg. அடுத்த வாரம் 10% விலை உயர்வு எதிர்பார்க்கப்படுகிறது.",
        chatPrompt3 = "இந்த சீசனில் பயிரிட சிறந்த பயிர் எது?",
        chatResponse3 = "உங்கள் இடம் மற்றும் மண் வகையின் அடிப்படையில், இந்த சீசனில் நிலக்கடலை அல்லது மக்காச்சோளம் பயிரிட நான் பரிந்துரைக்கிறேன். இவற்றில் ஏதேனும் ஒரு விரிவான அறிக்கை வேண்டுமா?",
        dashboardTitle = "டேஷ்போர்டு",
        marketPriceTitle = "சந்தை விலை முன்னறிவிப்பு",
        cropTomato = "பயிர்: தக்காளி",
        currentPrice = "தற்போதைய விலை: ₹45/kg",
        forecast = "முன்னறிவிப்பு: ₹52/kg",
        profitLossTitle = "லாபம் மற்றும் நஷ்டம் பகுப்பாய்வு",
        totalInvestment = "மொத்த முதலீடு: ₹25,000",
        expectedRevenue = "எதிர்பார்க்கப்படும் வருவாய்: ₹35,000",
        netProfit = "நிகர லாபம்: ₹10,000 (40%)",
        storiesTitle = "வெற்றிக் கதைகள்",
        storyCardTitle = "ரமேஷின் வெற்றிக் கதை",
        storyCardSubtitle = "ரமேஷ் குமார், பஞ்சாப் • 2 ஏக்கர் கோதுமைப் பண்ணை",
        storyCardContent = "குறைந்த கோதுமை மகசூல் மற்றும் அதிகரித்த உள்ளீட்டுச் செலவுகளால் ரமேஷ் சிரமப்பட்டார். அவரது பாரம்பரிய விவசாய முறைகள் அவரது குடும்பத்திற்குத் தேவையான லாபத்தைத் தரவில்லை.",
        readStoryButton = "இந்த கதையை உங்கள் பண்ணைக்கு எப்படிப் பயன்படுத்துவது என்று அக்ரிடியூட்டிடம் கேளுங்கள்",
        profileTitle = "பயனர் சுயவிவரம்",
        profileName = "பயனர்பெயர்: ஜான் டோ",
        llmGenerating = "பதில் உருவாக்கப்படுகிறது...",
        profileLocation = "இடம்: சென்னை, தமிழ்நாடு",
        profileFarmSize = "பண்ணையின் அளவு: 5 ஏக்கர்",
        settingsTitle = "அமைப்புகள்",
        languageSettings = "மொழி",
        loadingMessage = "தரவு ஏற்றப்படுகிறது...",
        errorMessage = "தரவு ஏற்றும் போது பிழை ஏற்பட்டது.",
        noDataMessage = "தரவு இல்லை.",
        priceTrend = "விலை போக்கு விளக்கப்படம்",
        averagePrice = "சராசரி விலை",
        currency = "₹/kg",
        market = "சந்தை",
        weatherAlert = "வானிலை எச்சரிக்கை",
        dummyWeatherAlert = "உங்கள் பகுதியில் கனமழை எதிர்பார்க்கப்படுகிறது. பயிர்களை பாதுகாக்க தேவையான முன்னெச்சரிக்கை நடவடிக்கைகளை மேற்கொள்ளவும்.",
        voiceInput = "குரல் உள்ளீடு",
        attachFile = "கோப்பை இணை",
        speechToTextPrompt = "இப்போது பேசுங்கள்...",
        tomatoPrice = "தக்காளி: ₹30 - ₹60 / கிலோ",
        onionPrice = "வெங்காயம்: ₹20 - ₹40 / கிலோ",
        weatherTitle = "வானிலை",
        // New strings
        chatHistory = "சாட் வரலாறு",
        deleteHistory = "வரலாற்றை நீக்கு",
        listening = "கேட்டுக்கொண்டிருக்கிறது...",
        enterMessage = "உங்கள் செய்தியை உள்ளிடவும்",
        send = "அனுப்பு",
        deleteChatHistory = "சாட் வரலாற்றை நீக்கு",
        deleteConfirmation = "உறுதியாக சாட் வரலாற்றை நீக்க விரும்புகிறீர்களா?",
        delete = "நீக்கு",
        cancel = "ரத்து செய்",
        askQuestion = "கேள்வி கேட்கவும்..."
    )
}
